### ISSUE TITLE
Flaky tests in CI on Windows/Node 16

### ISSUE THREAD

**Issue by kibertoad** [nodejs/undici#1460]
## Bug Description

Tests in CI, specifically Windows/Node 16, fail like this:

```
not ok 9 - test/fetch/headers.js # time=4518.838ms
  ---
  env: {}
  file: test/fetch/headers.js
  timeout: 60000
  command: C:\hostedtoolcache\windows\node\16.15.0\x64\node.exe
  args:
    - --expose-gc
    - --experimental-wasm-simd
    - test/fetch/headers.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: D:\a\undici\undici
  exitCode: null
  signal: SIGTERM
  ...
```

It can be another test, but still same error:
```
not ok 58 - test/redirect-stream.js # time=4544.734ms
  ---
  env: {}
  file: test/redirect-stream.js
  timeout: 60000
  command: C:\hostedtoolcache\windows\node\16.14.2\x64\node.exe
  args:
    - --expose-gc
    - --experimental-wasm-simd
    - test/redirect-stream.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: D:\a\undici\undici
  exitCode: null
  signal: SIGTERM
  ...
```

## Reproducible By

Rerunning CI several times, it fails approximately 1 out of 3 times.

## Expected Behavior

All tests always pass in CI.

## Environment

Microsoft Windows Server 2022 10.0.20348 / Node 16.14.2, Node 16.15.0

### Additional context

Earliest known occurrence: https://github.com/nodejs/undici/commit/ac3191e5430756e7d83aa039ffca13dcf3e35b54
